version: '3.4'
services:
  k6:
    image: loadimpact/k6:latest
    command: run -e DOMAIN=https://digitalassets.cvshealth.com -e IMAGETYPE=scene7-url-6 -e FLATTEN= /scripts/test.js
    volumes:
      - ./scripts:/scripts 
