version: '3.4'
services:
  k6:
    image: loadimpact/k6:latest
    command: run -e DOMAIN=https://s7d1.scene7.com/ -e IMAGETYPE=scene7-url -e FLATTEN= /scripts/test.js
    volumes:
      - ./scripts:/scripts 
